const Books = [
	{ id: 1,
		title: 'From Blood and Ashes',
		author: 'Jennifer L. Armentrout',
		img: 'https://m.media-amazon.com/images/I/51nh3JnQNsL.jpg',
		link: 'https://www.amazon.com/gp/product/B086JMSSVH?pf_rd_r=8JV9FCMVXJP96D02HTAF&pf_rd_p=edaba0ee-c2fe-4124-9f5d-b31d6b1bfbee&pd_rd_r=87b591b8-f515-4f36-8357-99e96d754205&pd_rd_w=5wxBz&pd_rd_wg=TqY6M&ref_=pd_gw_unk',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
		category: 'Fantasy'
	},
	{
		id: 2,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 3,
		title: 'The Hating Game: A Novel',
		author: 'Sally Thorne',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 4,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 5,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 6,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 7,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 8,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 9,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	},
	{
		id: 10,
		title: 'The Invisible Life of Addie LaRue',
		author: 'V. E. Schwab',
		img: 'https://m.media-amazon.com/images/I/51FVPBt51ZL.jpg',
		link: 'https://www.amazon.com/Invisible-Life-Addie-LaRue-ebook/dp/B084357H23/ref=sr_1_1?crid=1F2QKE4NO32SV&dchild=1&keywords=the+invisible+life+of+addie+larue+by+v.e.+schwab&qid=1605208117&sprefix=the+in%2Caps%2C250&sr=8-1',
		description: 'I never saw a more promising inclination; he was growing quite inattentive to other people, and wholly engrossed by her. Every time they met, it was more decided and remarkable. At his own ball he offended two or three young ladies, by not asking them to dance; and I spoke to him twice myself, without receiving an answer. Could there be finer symptoms? Is not general incivility the very essence of love?',
	}
];

export default Books;